<a href="https://colab.research.google.com/github/Riyasingh22600/ml-fundamentals-assignment/blob/main/ch1-2_notes/ch3_numpy_pandas/ch3_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 3: NumPy & Pandas

---

# Chapter 3 – NumPy & Pandas

## 3.1 Introduction to NumPy



In [3]:
# --- Install (only in Colab, skip if local Jupyter) ---
# !pip install numpy pandas matplotlib seaborn scikit-learn

# --- Imports ---
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# --- Creating arrays ---
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", arr_1d)
print("2D Array:\n", arr_2d)

# --- Array properties ---
print("Shape of 2D array:", arr_2d.shape)
print("Data type:", arr_1d.dtype)
print("Number of dimensions:", arr_2d.ndim)

# --- Mathematical operations ---
data = np.array([10, 20, 30, 40, 50])
print("Mean:", np.mean(data))
print("Standard deviation:", np.std(data))
print("Sum:", np.sum(data))

# --- Array creation functions ---
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
random_array = np.random.rand(3, 3)

print("Zeros array:\n", zeros)
print("Ones array:\n", ones)
print("Random array:\n", random_array)

# --- Array indexing and slicing ---
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Elements 2 to 5:", arr[2:6])
print("Every second element:", arr[::2])
print("Elements greater than 5:", arr[arr > 5])

# --- Matrix operations ---
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("Matrix multiplication:\n", np.dot(matrix_a, matrix_b))
print("Element-wise multiplication:\n", matrix_a * matrix_b)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape of 2D array: (2, 3)
Data type: int64
Number of dimensions: 2
Mean: 30.0
Standard deviation: 14.142135623730951
Sum: 150
Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Random array:
 [[0.99621487 0.64430895 0.62653816]
 [0.59642431 0.8384977  0.83616148]
 [0.99698583 0.77255016 0.86161208]]
Elements 2 to 5: [2 3 4 5]
Every second element: [0 2 4 6 8]
Elements greater than 5: [6 7 8 9]
Matrix multiplication:
 [[19 22]
 [43 50]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]


## Objective
Describe briefly what this chapter covers.

## TODO: Code Examples
Paste and run code examples from the PDF here.

## Results / Plots
Add outputs, figures, or screenshots here.

## Insights
Write 2–3 bullet points of what you learned.